jdhao/nvim-config

docs/Nvim_setup.sh
Hi, first of all many thanks for your sharing! Save my day.
I was trying your scripts today and noticed that the Nvim_setup.sh was not working properly. I have made the following two changes to make it work:
1. line 99 tries to extract a zipped file which would be downloaded later(at line 105), and then line 112 will extract that file again, except that it's using wrong arguments "zxvf".  
fix: comment out line 99, fix line 112 args from "zxvf" to "xvf"
2. typo at line 116, I think it should be "NODE_DIR", it was "NVIM_DIR", which hasn't be installed yet.
=> use xvf to extract node; fix a typo

core/autocommands.vim
If current buf in remaning two or more windows are filetypes in the quit
list, we should also quit nvim also.
=> [fix] quit does not work for 2 windows

lua/config/statusline.lua
The plugin whitespace.nvim has changed its internal implementation.
It is not reliable to depend on external plugins.
=> fix: trailing white sapces do not show as expected

lua/config/statusline.lua
Lualine's builtin diff often disappears and is not reliable, which is really frustrating for me.
=> use gitsigns for diff

lua/config/gitsigns.lua
Also tweak the highlight for word diff to make clear. The default highlgiht for word diff is TermCursor, which is unreadable.
=> enable word diff for gitsigns.nvim

core/plugins.vim, lua/plugins.lua
1. Change autocmd for buffers started by firenivm, it seems that BufNewFile does not work as intended, in contrast, BufEnter, BufRead, BufWinEnter seem to work.
2. Disable several plugins if we are using firenvim, these plugins include dashboard-nvim, lualine, bufferline.nvim
=> update conf related to firenvim

lua/config/hlslens.lua, lua/plugins.lua
The * can now search selected text by default. The cursor stay feature can also be simulated.
=> remove vim-asterisk

core/globals.lua
The issue has been fixed in https://github.com/neovim/neovim/pull/19139.
=> remove language workaround for macOS

after/ftplugin/cpp.vim, after/ftplugin/javascript.vim, after/ftplugin/lua.vim, after/ftplugin/python.vim, after/ftplugin/sql.vim, after/ftplugin/toml.vim, after/ftplugin/vim.vim, after/ftplugin/yaml.vim, core/options.vim
This removes a lot of code duplication. If we want to use 4 spaces, we can set it separately in their ftplugin settings.
=> use 2 spaces for tabs by default

lua/config/statusline.lua
For the details, see https://jdhao.github.io/2021/02/25/nvim_ime_mode_auto_switch/.
=> fix: make xkbswitch work on mac M1 CPU

after/ftplugin/lua.vim, after/ftplugin/vim.vim
Otherwise, the mapping will be global and leak to unrelated to files.
=> make filetype mapping local

lua/config/lsp.lua
It is not necessary to install clangd if the user does not use neovim with CPP/C.
=> fix: omit the clangd missing message, close #180

README.md, lua/config/nvim-tree.lua, lua/plugins.lua
Two changes for nvim-tree:
1. `require("nvim-tree").toggle(false, true)` was removed about 2 weeks ago. 
* After running `PackerSync` yesterday, I started getting the error `lua/config/nvim-tree.lua:117: attempt to call field 'toggle' (a nil value)`.
* see https://github.com/nvim-tree/nvim-tree.lua/issues/2054#issuecomment-1467031808
2. kyazdani42 has redirected their repos to nvim-tree/nvim-tree
=> nvim-tree: fix shortcut and repo

init.lua, lua/plugins.lua
It is not needed since nvim 0.9.0
=> remove impatient.nvim

lua/config/lsp.lua
Use separate key mappings to show diagnostics for the current buffer and all opened files.
=> feat: update diagnostic mappings

lua/config/bufferline.lua, lua/config/dashboard-nvim.lua, lua/config/lsp.lua, lua/config/statusline.lua
Since wezterm upgrade its support for Nerd Fonts 3.0, we should update the codepoints used for some of the Unicode Icons. Their code points are changed due to breaking changes in Nerd Fonts.
=> fix: missing nerdfonts

init.lua
The cache should be invalidated. This fix does not work 100%, because, e.g., there are other configs hiding deeper under lua/config/ directory. A restart is the best way to reload the config.
=> fix: user lua conf reloading fails

lua/custom-autocmd.lua, lua/mappings.lua
The previous way of keep the cursor while yanking is not perfect. It will break multi-line yank (`{count}yy`).
=> fix multi-line yank issue, close #220

lua/custom-autocmd.lua
For TextYankPost event, it includes both yank and delete, we should only restore cursor position for yank, not for delete. Otherwise, it messes up with text deletion when you visually select multiple lines and delete them. See also issue reported here: https://github.com/jdhao/nvim-config/pull/222#issuecomment-1698634645
=> fix multi visual line delete issue

lua/config/hlslens.lua
The captured error message is not correct before.
=> fix hlslens issue when no pattern is found

lua/plugins.lua
It seems that if we use `VeryLazy` for bufferline, it will not work properly.
=> fix bufferline loading issue

init.lua
Other version of nvim can still run this config, but should use with care.
Close PR #217
=> Loosen the version check condition

lua/config/nvim-tree.lua, lua/custom-autocmd.lua
Now when you open a directory when starting nvim, nvim-tree will be opened to handle the directory correctly, see also issue #257.
=> Enable nvim-tree to open dir during startup

lua/config/statusline.lua
The percent location is useless and just noise.
=> Stop showing percent location

lua/mappings.lua
1. fix a typo in gJ mapping when setting the mark, the correct syntax is `mz` (set mark `z`), not `zm`
2. fix bug with `iB` text object: previously `viB` does not work as expected, because it does not select the entire buffer as expected. After much investigation, I found it is because the `<cmd>` mapping argument. If we use `<cmd>` argument for mapping, the mode does not change. So if we use `viB`, inititally we are still in visual mode. Later in the implementation, when we use `` normal! `<V`>  `` to select the entire buffer, it interferes with original visual mode. As a result, the entire buffer is not selected. In the text obj implementation, we can use `exe "normal! \<Esc>"` to clear the visual mode and make `viB`, but this is not ideal. I think it is eaiser to just not use the …
=> update some mappings

lua/config/statusline.lua
- rearrange a few components
- add and remove a few components
=> update lualine config

lua/plugin_specs.lua
In lazy.nvim, the `build` parameter accept value in different format. If the value is
1. a string and starts with `:`, it will be treated as vim command
2. a string and starts without `:`, it will be treated as shell command
3. a function. Lazy.nvim will run this function
I compared closely between case 1 and case 3. In case 1, when lazy.nvim runs the viml command, the runtimepath is already populated with the current plugin we are trying to build.
However in case 3, the runtimepath is not populated with the plugin path, which means that any command you run by this plugin is not available.
So I did it in a hacky way to add the plugin path to runtimepath manually, and source it manually using `:runtime` command. The `: runtime` command is needed because in the init process, adding the …
=> Fix firenvim and LeaderF build issues

after/ftplugin/lua.vim, after/ftplugin/python.vim, lua/plugin_specs.lua
1. For python and lua, rely on LSP for folding
2. show fold signs on the right of the number column
=> update config related to folding

lua/config/nvim-statuscol.lua, lua/plugin_specs.lua
Only show fold signs for fold level below a certain level to avoid clutter the left side columns with a lot of folding signs
=> filter fold level sign for statuscol.nvim

lua/config/nvim-cmp.lua, lua/plugin_specs.lua, viml_conf/options.vim
1. restrict max width of the completion menu. Here I am using lspkind.nvim to achieve this. There are other native ways to do this, see also https://github.com/hrsh7th/nvim-cmp/discussions/609 and https://github.com/hrsh7th/nvim-cmp/issues/980
2. remove cmp-emoji as it is rarely used and interfere when I write Python
3. lower the transparency for popup menu
=> Update configuration for nvim-cmp

lua/config/hlslens.lua
By default, when you press `*` to search word under the cursor, the option `smartcase` is ignored. This means that if you press `*` when your cursor is on `The`, the lower case one `the` is also searched.
In this commit, we translate star and # search into normal search so that 'smartcase' option is respected.
=> Make * and # search case aware

lua/config/lsp.lua, lua/globals.lua
Nvim nows provides `vim.inspect()` and `vim.print()`.
=> remove inspect() from lua _G table

init.lua
Full path should be used to load viml config, otherwise, when we open nvim in other directories, we see errors that the viml config can not be found.
=> Use absolute path for viml config

lua/config/live-command.lua
The config for live-command is updated to the latest version, see also https://github.com/smjonas/live-command.nvim/issues/39
=> update conf for plugin live-command.nvim

lua/config/lsp.lua
The client side inlayhint can be enabled by uncommentting the code in this PR.
=> enable inlayhint for lua_ls server

plugin/command.lua
the string.gsub in lua is not flexible and use vim.fn.substitute() instead.
=> Fix command CopyPath issue

after/ftplugin/lua.vim, lua/config/lsp.lua
We need to disable the mapping set for LSP, otherwise the mapping set in lua.vim will be overridden.
=> silently format lua file using stylua

lua/config/lualine.lua
make everything async and non-blocking and also remove the branch name fetching. It is not needed if we use the `@{upstream}` notation.
=> Lualine async git info

lua/config/gitsigns.lua, lua/config/lualine.lua
I guess it is due to the reason that we are doing constant git fetch, and somehow gitsigns word diff is affected.
Changing the gitsigns debounce or changing lualine refresh rate do not seem to help. So gitsigns word diff is disabled.
=> fix gitsign word_diff flickering issue

lua/plugin_specs.lua
It's my first time using neovim. I use archlinux and got some errors using this setup since treesitter will only be installed on mac os. This conflicts with treesitter-textobjects which gets installed for every system.
With this change treesitter will be installed on every system.
=> Install Treesitter on all systems

after/lsp/bashls.lua, after/lsp/clangd.lua, after/lsp/ltex.lua, after/lsp/lua_ls.lua, after/lsp/pyright.lua, after/lsp/ruff.lua, after/lsp/vimls.lua, lua/config/lsp.lua, lua/lsp_utils.lua
In this new structure, the main configuration for a LSP server is provided by the plugin nvim-lspconfig.
Some of the config may be overridden by the configuration under directory `after/lsp/xxx.lua`, where `xxx` is the lsp server name used by nvim-lspconfig.
Note that it is necessary to put the custom lsp server configuration under `after/` directory, in order to correctly override the config provided by nvim-lspconfig.
=> Use new lsp configuration structure

lua/plugin_specs.lua
It seems that for nvim 0.11.2, if you open nvim and then use fzf-lua to open a file, the filetype event is not set. This has something to do with changes in this PR: https://github.com/neovim/neovim/pull/33702. See also this post: https://www.reddit.com/r/neovim/comments/1l7pz1l/starting_from_0112_i_have_a_weird_issue/
=> Fix filetype detection issue for nvim 0.11.2

lua/plugin_specs.lua
- pin gitsigns to stable version, to avoid https://github.com/lewis6991/gitsigns.nvim/issues/1381
- add plugin quicker.nvim
=> update plugin specs

lua/config/lsp.lua, lua/diagnostic-conf.lua, lua/mappings.lua
- use `close_events` to close floating win created by hover or diagnostics easily
- define a mapping for `<Esc>` to dismiss all floating win
=> feat: close float win more easily when not needed
