jdhao/nvim-config

lua/custom-autocmd.lua
lua/plugins.lua

Also move the autocmd location.

chore: add notification for packer compile

---

core/colorschemes.lua
lua/plugins.lua

- remove other gruvbox variant
- remove doom-one casue it has bugs
- add more colorschemes

update colorscheme list

---

lua/config/lsp.lua

https://valentjn.github.io/ltex/ltex-ls/installation.html

Add ltex-ls support to lsp.

---

docs/nvim_setup_linux.sh
docs/nvim_setup_windows.ps1
lua/config/lsp.lua

The lua language server from sumneko had changed its repo and created a new organizational repo. See also https://github.com/neovim/nvim-lspconfig/pull/2439.

refactor: lua language server rename

---

lua/config/statusline.lua

Do not show it in far right, move it to the left side for easier visibility.

feat: update diagnostic position in statusline

---

lua/config/lsp.lua

1. support using black as formatter
2. replace obsolete pyls-isort with maintained ones

feat: update pylsp conf

---

lua/config/lsp.lua

Specify the correct python executable path for mypy to work well.

feat: support venv in Mypy

---

core/plugins.vim

feat: more ignore files for LeaderF

---

lua/config/git-linker.lua

1. Add configuration for azure devops
2. change the mappings slightly

update git-linker conf

---

core/options.vim

disable horizontal scroll by mouse

---

lua/colorschemes.lua
lua/plugin_specs.lua

1. remove some colorscheme that doesn't work well with Markdown
2. change how the colorscheme conf is organized.

Update colorscheme conf

---

lua/config/lsp.lua
lua/plugin_specs.lua

Seee also this https://github.com/neovim/neovim/pull/24493

remove emmylua since neovim has builtin annotation

---

README.md
after/ftplugin/cpp.vim
after/ftplugin/lua.vim
after/ftplugin/python.vim
lua/plugin_specs.lua

delimitMate is not updated for a long time.

use plugin nvim-autopairs for autopair

---

lua/plugin_specs.lua

1. fix build issue
2. fix PATH env issue

make firenvim work again

---

lua/config/nvim_ufo.lua
lua/plugin_specs.lua
viml_conf/options.vim

The settings are copied from https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1514537245, with some modification.

use plugin nvim-ufo for better folding

---

lua/config/fugitive.lua

`<cmd> `mapping must end with `<CR>`

fix git mapping issue

---

lua/config/lsp.lua

The removed settings are already set by lazydev.nvim.

remove lua_ls conf in favor of lazydev.nvim

---

lua/config/bufferline.lua

Do not show buffer number and use a mapping to pick buffer instead.

update config for bufferline.nvim

---

lua/custom-autocmd.lua

Add error handling for resuming the cursor

---

lua/plugin_specs.lua

Until cmp is maintained again or switch??

use a cmp-fork for now

---

viml_conf/plugins.vim

Only search file content and not file name when using Leaderf rg

update Leaderf setting

---

lua/config/lsp.lua

pyright servers type checking, completion, and ruff servers linting and diagnostics (ruff can also format Python files, but it is slightly different from black)

Switch Python LSP for completion and add ruff

---

lua/config/lsp.lua

see my comment here for the details: https://www.reddit.com/r/neovim/comments/1gdv1rc/comment/lvt9nlm/

use plaintext for pyright hover request

---

lua/config/lualine.lua
viml_conf/options.vim

Related issues:
+ https://groups.google.com/g/vim_dev/c/YwFLUaduXTQ
+ https://github.com/neovim/neovim/pull/21202
+ https://github.com/nvim-lualine/lualine.nvim/issues/949

make option showcmd shown in statusline instead

---

README.md
init.lua
lua/plugin_specs.lua
viml_conf/plugins.vim

update supported nvim version to latest stable

---

lua/plugin_specs.lua

options for `win` can be found here: https://github.com/folke/snacks.nvim/blob/main/docs/win.md

snack config update

---

lua/custom-autocmd.lua

This conflicts with the fuzzy finder, if you grep for a word using fuzzy finder and then press enter to go to the place, it does not work anymore, it will go the line where you are last time.

remove automcd to go to last place

---

lua/config/lualine.lua

- components are re-ordered
- add new component to show git ahead/behind info
- remove some unused component

Update lualine config

---

lua/config/lsp.lua

Now nvim-lspconfig serves as ready made configuration for different lsp server configurations.
See also related PR in lspconfig: https://github.com/neovim/nvim-lspconfig/pull/3659

use new api vim.lsp.config for lsp configuration

---

lua/config/lsp.lua

- eliminate duplicated definitions from LSP
- enable yaml language server

update LSP config
